import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {connectMcp} from './client.js';
import {room,roomWalls} from '../build-primitives/index.js';
const {client,call}=await connectMcp();
const bounds={min:[0,100,0],max:[14,108,14]};
const evidence:any={at:new Date().toISOString(),path:'MCP SDK stdio client → TS MCP → authenticated HTTP → Paper → WorldEdit → world',checks:[]};
const checked=(name:string)=>{evidence.checks.push(name);console.log(`PASS ${name}`);};
try{
  const tools=await client.listTools();assert.ok(tools.tools.length>=13);checked(`${tools.tools.length} discoverable MCP tools`);
  evidence.server=await call('world.get_summary');
  const mara=await call('world.get_entities',{bounds:{min:[86,100,82],max:[89,105,85]}});
  assert.ok(mara.entities.some((e:any)=>e.type==='VILLAGER'));
  assert.ok(mara.entities.some((e:any)=>e.type==='TEXT_DISPLAY'));
  checked('persistent glowing Mara NPC and interaction label exist at the onboarding path');
  evidence.gameplay=await call('gameplay.run_self_test');assert.equal(evidence.gameplay.status,'PASS');
  const packResponse=await fetch('http://127.0.0.1:38765/pack');assert.equal(packResponse.status,200);
  const packBytes=Buffer.from(await packResponse.arrayBuffer());assert.ok(packBytes.length>100&&packBytes.length<100000);checked('canonical gameplay file-persistence self-test and small pack endpoint (not real-player integration)');
  assert.match(evidence.server.server,/26\.2/);assert.match(evidence.server.worldedit,/7\.4\.5/);
  const baseline=await call('world.get_blocks',{bounds});
  assert.equal(Object.values(baseline.blocks).filter(b=>b!=='minecraft:air').length,0,'fixture must start as all air; refuse to erase user work');
  evidence.baseline=baseline.checksum;
  assert.deepEqual((await call('world.get_entities',{bounds})).entities,[]);
  const snapshot=await call('snapshot.create',{name:'original-air-fixture',bounds});
  const t=await call('build.begin_transaction',{name:'test.chamber',bounds});
  const transactionId=t.transactionId;
  for(const f of room([0,100,0]))await call('build.fill_region',{transactionId,...f});
  const preview=await call('build.dry_run',{transactionId});
  assert.equal(preview.changedBlocks,824);assert.equal(preview.volume,2025);
  assert.deepEqual((await call('world.get_blocks',{bounds})).blocks,baseline.blocks);checked('begin, stage and dry-run do not mutate any fixture block');
  const commitArgs={transactionId,previewHash:preview.previewHash,requestId:randomUUID()};
  const committed=await call('build.commit_transaction',commitArgs);assert.equal(committed.changedBlocks,824);
  assert.deepEqual(await call('build.commit_transaction',commitArgs),committed);checked('commit retry uses durable identical receipt');
  await assert.rejects(call('build.commit_transaction',{...commitArgs,previewHash:'0'.repeat(64)}),/REQUEST_ID_REUSED/);
  const built=await call('world.get_blocks',{bounds});assert.equal(Object.values(built.blocks).filter(b=>b==='minecraft:stone_bricks').length,824);
  evidence.room=built.checksum;evidence.roomChangedBlocks=824;checked('WorldEdit committed exact 824-block room');
  const variation=await call('build.begin_transaction',{name:'wall-age-pass',bounds});
  for(const wall of roomWalls([0,100,0]))await call('build.replace_palette',{transactionId:variation.transactionId,bounds:wall,from:'minecraft:stone_bricks',to:'minecraft:cracked_stone_bricks',percent:20,seed:42});
  const v=await call('build.dry_run',{transactionId:variation.transactionId});assert.equal(v.changedBlocks,74);
  await call('build.commit_transaction',{transactionId:variation.transactionId,previewHash:v.previewHash});
  const aged=await call('world.get_blocks',{bounds});assert.equal(Object.values(aged.blocks).filter(b=>b==='minecraft:cracked_stone_bricks').length,74);
  await assert.rejects(call('build.undo',{transactionId}),/UNDO_CONFLICT/);checked('undo refuses to overwrite newer world edits');
  await call('build.undo',{transactionId:variation.transactionId});assert.deepEqual((await call('world.get_blocks',{bounds})).blocks,built.blocks);
  const repeat=await call('build.begin_transaction',{name:'repeat-seed',bounds});
  for(const wall of roomWalls([0,100,0]))await call('build.replace_palette',{transactionId:repeat.transactionId,bounds:wall,from:'minecraft:stone_bricks',to:'minecraft:cracked_stone_bricks',percent:20,seed:42});
  const vr=await call('build.dry_run',{transactionId:repeat.transactionId});assert.equal(vr.previewHash,v.previewHash);
  await call('build.rollback_transaction',{transactionId:repeat.transactionId});checked('20 percent wall variation selects 74 deterministic blocks and undoes exactly');
  await call('build.rollback_transaction',{transactionId});assert.deepEqual((await call('world.get_blocks',{bounds})).blocks,baseline.blocks);checked('room rollback matches every original block state');
  await assert.rejects(call('build.begin_transaction',{name:'outside',bounds:{min:[-1,100,0],max:[1,101,1]}}),/OUTSIDE/);
  await assert.rejects(call('build.begin_transaction',{name:'protected',bounds:{min:[30,100,30],max:[31,101,31]}}),/PROTECTED/);
  await assert.rejects(call('build.begin_transaction',{name:'large',bounds:{min:[0,96,0],max:[31,127,31]}}),/VOLUME/);checked('MCP rejects outside, protected and excessive volume');
  const token=(await readFile('.runtime/token','utf8')).trim();
  const direct=async (tool:string,args:any,auth=token,headers:Record<string,string>={})=>{
    const r=await fetch('http://127.0.0.1:38765/rpc',{method:'POST',headers:{Authorization:`Bearer ${auth}`,'Content-Type':'application/json',...headers},body:JSON.stringify({requestId:randomUUID(),actor:'fixture-direct',prompt:'Adversarial independent bridge validation',tool,args})});return {status:r.status,body:await r.json() as any};
  };
  assert.equal((await direct('world.get_summary',{},'incorrect')).status,401);
  assert.equal((await direct('world.get_summary',{},token,{Origin:'https://example.com'})).status,403);
  for(const [b,message] of [[{min:[-1,100,0],max:[1,101,1]},'OUTSIDE'],[{min:[30,100,30],max:[31,101,31]},'PROTECTED'],[{min:[0,96,0],max:[31,127,31]},'VOLUME']] as const){const r=await direct('build.begin_transaction',{name:'reject',bounds:b});assert.equal(r.body.ok,false);assert.match(r.body.error,new RegExp(message));}
  assert.match((await direct('run_command',{command:'stop'})).body.error,/UNKNOWN_TOOL/);checked('bridge independently enforces token, Origin, bounds, protected regions, volume and allowlist');
  const small={min:[0,100,0],max:[0,100,0]};
  const edit=await call('build.begin_transaction',{name:'snapshot-change',bounds:small});
  await call('build.fill_region',{transactionId:edit.transactionId,bounds:small,block:'minecraft:stone'});
  const ep=await call('build.dry_run',{transactionId:edit.transactionId});await call('build.commit_transaction',{transactionId:edit.transactionId,previewHash:ep.previewHash});
  const restore=await call('snapshot.stage_restore',{snapshotId:snapshot.snapshotId});assert.equal((await call('world.get_blocks',{bounds:small})).blocks['0,100,0'],'minecraft:stone');
  const rp=await call('build.dry_run',{transactionId:restore.transactionId});await call('build.commit_transaction',{transactionId:restore.transactionId,previewHash:rp.previewHash});
  assert.deepEqual((await call('world.get_blocks',{bounds})).blocks,baseline.blocks);checked('snapshot restore is staged then committed and matches original fixture');
  const audit=(await readFile('server-dev/plugins/WorldAgent/audit.jsonl','utf8')).trim().split('\n').map(s=>JSON.parse(s));
  const record=audit.find(r=>r.request.requestId===commitArgs.requestId);assert.equal(record.request.actor,'fixture-suite');assert.equal(record.result.changeId,transactionId);assert.ok(record.request.prompt);checked('durable audit joins actor, prompt, tool, request, transaction and change');
  evidence.final=(await call('world.get_blocks',{bounds})).checksum;assert.equal(evidence.final,evidence.baseline);
  evidence.status='PASS';
}catch(e){evidence.status='FAIL';evidence.error=String(e);throw e;}
finally{await mkdir('reports',{recursive:true});await writeFile('reports/connected-world.json',JSON.stringify(evidence,null,2));await client.close();}
